### PR TITLE
Using jest with selenium 

### PR DESCRIPTION
**Pull request by TacEtarip**

### CODE REVIEW

**Comment by jrichardsz** [comment]
- improve readme specifying what is the default used browser
- fix image on readme

**Comment by jrichardsz** [comment]
I ran it but I got this error:

```
> selenium-nodejs-starter@1.0.0 start /tmp/workspace/selenium-nodejs-starter
> jest --verbose --json --outputFile=jest-output.json && node .

 PASS  usil/marketing/google-seo/shouldAppearFirstFour/shouldAppearFirstFour.test.js (8.371 s)
  Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search
    ✓ Link for the USIL appears in the first 4 positions (4560 ms)
    ✓ Link for the coloring dreams appears in the first 4 positions (3078 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        8.429 s
Ran all test suites.
Test results written to: jest-output.json
/tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:188
      var contents = item.toString().split("\n").reduce(function (memo, l) {
                          ^

TypeError: Cannot read property 'toString' of undefined
    at /tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:188:27
    at Array.forEach (<anonymous>)
    at generateRow (/tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:187:11)
    at /tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:281:16
    at Table.forEach (<anonymous>)
    at Table.toString (/tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:264:10)
    at Object.<anonymous> (/tmp/workspace/selenium-nodejs-starter/index.js:35:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

Commands:

- npm install
- npm run start

Environment:

- node : 14
- ubuntu 18

generated jest-output.json:

```
{"numFailedTestSuites":0,"numFailedTests":0,"numPassedTestSuites":1,"numPassedTests":2,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":1,"numTotalTests":2,"openHandles":[],"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesRemovedList":[],"filesUnmatched":0,"filesUpdated":0,"matched":0,"total":0,"unchecked":0,"uncheckedKeysByFile":[],"unmatched":0,"updated":0},"startTime":1638216497666,"success":true,"testResults":[{"assertionResults":[{"ancestorTitles":["Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search"],"failureMessages":[],"fullName":"Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search Link for the USIL appears in the first 4 positions","location":null,"status":"passed","title":"Link for the USIL appears in the first 4 positions"},{"ancestorTitles":["Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search"],"failureMessages":[],"fullName":"Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search Link for the coloring dreams appears in the first 4 positions","location":null,"status":"passed","title":"Link for the coloring dreams appears in the first 4 positions"}],"endTime":1638216506081,"message":"","name":"/tmp/workspace/selenium-nodejs-starter/usil/marketing/google-seo/shouldAppearFirstFour/shouldAppearFirstFour.test.js","startTime":1638216497710,"status":"passed","summary":""}],"wasInterrupted":false}
```

**Comment by jrichardsz** [comment]
What is the purpose of : 

image

**Comment by TacEtarip** [comment]
> What is the purpose of :
> 
> image

It imports the chromedriver that has been installed by npm, for more info take a look at [chromedriver](https://www.npmjs.com/package/).



> I ran it but I got this error:
> 
> ```
> > selenium-nodejs-starter@1.0.0 start /tmp/workspace/selenium-nodejs-starter
> > jest --verbose --json --outputFile=jest-output.json && node .
> 
>  PASS  usil/marketing/google-seo/shouldAppearFirstFour/shouldAppearFirstFour.test.js (8.371 s)
>   Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search
>     ✓ Link for the USIL appears in the first 4 positions (4560 ms)
>     ✓ Link for the coloring dreams appears in the first 4 positions (3078 ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       2 passed, 2 total
> Snapshots:   0 total
> Time:        8.429 s
> Ran all test suites.
> Test results written to: jest-output.json
> /tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:188
>       var contents = item.toString().split("\n").reduce(function (memo, l) {
>                           ^
> 
> TypeError: Cannot read property 'toString' of undefined
>     at /tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:188:27
>     at Array.forEach (<anonymous>)
>     at generateRow (/tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:187:11)
>     at /tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:281:16
>     at Table.forEach (<anonymous>)
>     at Table.toString (/tmp/workspace/selenium-nodejs-starter/node_modules/cli-table/lib/index.js:264:10)
>     at Object.<anonymous> (/tmp/workspace/selenium-nodejs-starter/index.js:35:19)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
> ```
> 
> Commands:
> 
> * npm install
> * npm run start
> 
> Environment:
> 
> * node : 14
> * ubuntu 18
> 
> generated jest-output.json:
> 
> ```
> {"numFailedTestSuites":0,"numFailedTests":0,"numPassedTestSuites":1,"numPassedTests":2,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":1,"numTotalTests":2,"openHandles":[],"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesRemovedList":[],"filesUnmatched":0,"filesUpdated":0,"matched":0,"total":0,"unchecked":0,"uncheckedKeysByFile":[],"unmatched":0,"updated":0},"startTime":1638216497666,"success":true,"testResults":[{"assertionResults":[{"ancestorTitles":["Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search"],"failureMessages":[],"fullName":"Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search Link for the USIL appears in the first 4 positions","location":null,"status":"passed","title":"Link for the USIL appears in the first 4 positions"},{"ancestorTitles":["Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search"],"failureMessages":[],"fullName":"Link https://www.usil.edu.pe/?verified=true appears on the first 4 positions in the google search Link for the coloring dreams appears in the first 4 positions","location":null,"status":"passed","title":"Link for the coloring dreams appears in the first 4 positions"}],"endTime":1638216506081,"message":"","name":"/tmp/workspace/selenium-nodejs-starter/usil/marketing/google-seo/shouldAppearFirstFour/shouldAppearFirstFour.test.js","startTime":1638216497710,"status":"passed","summary":""}],"wasInterrupted":false}
> ```

In windows file paths are separed with '\' in ubuntu with '/', this generated an error at the moment of separate the file path. It should now work.





> * improve readme specifying what is the default used browser
> * fix image on readme

Added an extra instruction, if you find an incomatible chrome version just use `npm install chromedriver --detect_chromedriver_version`

**Comment by jrichardsz** [comment]
fix jpg image on readme

**Comment by jrichardsz** [comment]
- centralize browser initialization: BrowserSettings.js getDriverBuild()
- browserOptions.json = 
{
"arguments": ['--headless','--no-sandbox', '--disable-dev-shm-usage']
}
- env variables usage for browser selection

```
export browser=chrome
npm install
npm run start
```


- https://stackoverflow.com/questions/56614874/selenium-doesnt-start-chrome-in-headless-mode-no-matter-what-i-do

**Comment by jrichardsz** [comment]
ignore jest-output.json

**Pull request closed without merging**
